#!/bin/bash

if [[ $# < 1 || $# > 2 ]]; then
    echo "Usage: $0 <directory or file path> [optional: output path]"
    exit 1
fi

java -cp target/GenJSONs-1.0-SNAPSHOT-jar-with-dependencies.jar edu.boisestate.cs.MainJSON $@
